language: python
dist: trusty
python:
  - "3.5"
# command to install dependencies

install: 
  - "pip install -r requirements.txt"
  - python setup.py install
  - pip install codecov
 - pip install pytest-cov
script: 
  - timeout --preserve-status 8s wikilabels dev_server
- py.test --cov=./
after_success:
- codecov
