language: "python"
sudo: true
python:
  - "3.5"
# command to install dependencies
before_install:
  # apt-get packages
  - sudo apt-get -qq update
  - sudo apt-get install -y postgresql 
  - sudo apt-get install -y libffi-dev 
  - sudo apt-get install -y npm 
  - sudo apt-get install -y g++ 
  - sudo apt-get install -y python3-dev 
  - sudo apt-get install -y libmemcached-de
  - sudo apt-get install -y postgresql-server-dev-all 
install: 
#pip and python installs
- "pip install -r requirements.txt"
- python setup.py install
script: 
- wikilabels dev_server &
- sudo useradd wikilabels
- sudo su postgres
- psql  [
  CREATE USER wikilabels WITH PASSWORD 'citest';
  CREATE DATABASE wikilabels;
 GRANT ALL PRIVILEGES ON DATABASE wikilabels to wikilabels;
 \q
- sleep(15) 
- pkill -f "wikilabels dev_server" 
