language: python
dist: jessie
python:
  - "3.5"
services:
    - postgresql

before_install:
  - npm install eslint stylelint@8.2.0 stylelint-config-wikimedia

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
  - pip install codecov pytest-cov flake8

before_script:
    - psql -c "CREATE USER wikilabels WITH PASSWORD 'wikilabels-admin';" -U postgres
    - psql -c "CREATE DATABASE wikilabels;" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE wikilabels to wikilabels;" -U postgres
    - psql wikilabels < wikilabels/database/schema.sql -U wikilabels
    - psql wikilabels < wikilabels/database/schema-testdata.sql -U wikilabels

script:
  - flake8 . --ignore=E722
  - timeout --preserve-status 8s wikilabels dev_server
  - ./node_modules/.bin/eslint .
  - ./node_modules/.bin/stylelint "wikilabels/wsgi/static/css/*.css"
  - pytest --cov=wikilabels -m "not nottravis"

after_success:
  - codecov

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-ai"
    on_success: change
    on_failure: change
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"
